[package]
name = "orinoco_proc_macro"
version = "0.1.1"
edition = "2024"
license-file = "LICENSE"
description = "Utility for Deriving RPC (Remote Procedure Call) boilerplate for calling trait methods on a remote object"
homepage = "https://github.com/brodiealexander/orinoco"
repository = "https://github.com/brodiealexander/orinoco"
readme = "README.md"

[lib]
proc-macro = true


[dependencies]

quote = "1.0"
proc-macro2 = "1.0.107"
anyhow = "1.0.104"
convert_case = "0.11.0"

[dependencies.syn]
version = "2.0"
features = ["full"]
